const LABELS = {
  gemini: 'Gemini',
  groq: 'Groq',
  ollama: 'Ollama (local)',
  openai: 'OpenAI',
  fallback: 'Offline template',
};

const STYLES = {
  gemini: 'bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/30',
  groq: 'bg-orange-500/10 text-orange-600 dark:text-orange-400 border-orange-500/30',
  ollama: 'bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/30',
  openai: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/30',
  fallback: 'bg-slate-500/10 text-slate-600 dark:text-slate-400 border-slate-500/30',
};

export default function ProviderBadge({ provider }) {
  if (!provider) return null;

  return (
    <span
      className={`inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[11px] font-semibold ${
        STYLES[provider] || STYLES.fallback
      }`}
      title={`This response was generated by ${LABELS[provider] || provider}`}
    >
      <span className="h-1.5 w-1.5 rounded-full bg-current" />
      {LABELS[provider] || provider}
    </span>
  );
}
